<?php

namespace AppBundle\Repository;

/**
 * BlazonShapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlazonShapeRepository extends \Doctrine\ORM\EntityRepository
{
}
