<?php

namespace AppBundle\Repository;

/**
 * JerseyShapeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class JerseyShapeRepository extends \Doctrine\ORM\EntityRepository
{
}
