<?php

namespace AppBundle\Repository;

/**
 * PlayerGKStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerGKStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
