<?php

namespace AppBundle\Repository;

/**
 * PlayerSPEStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerSPEStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
