<?php

namespace AppBundle\Repository;

/**
 * PlayerATKStatsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerATKStatsRepository extends \Doctrine\ORM\EntityRepository
{
}
