<?php

namespace AppBundle\Repository;

/**
 * StoreItemRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StoreItemRepository extends \Doctrine\ORM\EntityRepository
{
}
