user:
    resource: "@UserBundle/Controller/"
    type:     annotation
    prefix:   /api/users
    defaults:
        _format: json
    methods:  [GET, POST, OPTIONS]

app:
    resource: '@AppBundle/Controller/'
    type: annotation

NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /api/doc

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"