admin:
    resource: "@AdminBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation

auth-tokens:
    type:     rest
    resource: AppBundle\Controller\AuthTokenController
