# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:

    providers:
        my_entity_users:
            entity:
                class: AppBundle:User

    firewalls:
        # disables authentication for assets and the profiler, adapt it according to your needs
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        secured_area:
            anonymous: ~
            logout:
                path:   /logout
                target: /

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            cost: 12
